name: Test CI
'on':
  pull_request:
    branches:
        - main
        - test
jobs:
  danger-ci:
    name: Danger CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
        env:
          RUNNER_TEMP: /tmp
      - name: yarn install
        run: yarn install
      - name: Danger CI
        uses: vtex/danger@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          REQUIRE_CHANGELOG_VERSION: false
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
        env:
          RUNNER_TEMP: /tmp
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: 'echo "::set-output name=dir::$(yarn cache dir)"'
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: '${{ steps.yarn-cache-dir-path.outputs.dir }}'
          key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Lint project
        run: |
            yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
        env:
          RUNNER_TEMP: /tmp
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: 'echo "::set-output name=dir::$(yarn cache dir)"'
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: '${{ steps.yarn-cache-dir-path.outputs.dir }}'
          key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run test
        run: |
            yarn test
